package model;
// Generated 23/07/2014 08:44:53 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Alunos generated by hbm2java
 */
@Entity
@Table(name="ALUNOS"
    ,schema="DBSM"
    , uniqueConstraints = @UniqueConstraint(columnNames="ID_PESSOA") 
)
public class Alunos  implements java.io.Serializable {


     private BigDecimal idAluno;
     private Pessoas pessoasByIdResponsavel;
     private Pessoas pessoasByIdPessoa;
     private BigDecimal idEscolaFund;
     private BigDecimal idEscolaMedio;
     private BigDecimal idLocalFund;
     private BigDecimal idLocalMedio;
     private BigDecimal idNaturalidade;
     private BigDecimal idTutorFin;
     private BigDecimal anoConcFund;
     private BigDecimal anoConcMedio;
     private BigDecimal cursoFundTab;
     private BigDecimal cursoFundItem;
     private BigDecimal cursoMedioTab;
     private BigDecimal cursoMedioItem;
     private Date dtNascimento;
     private BigDecimal estadoCivilTab;
     private BigDecimal estadoCivilItem;
     private BigDecimal nacionalidadeTab;
     private BigDecimal nacionalidadeItem;
     private String nomeMae;
     private String nomePai;
     private String sexo;
     private String tipoSanguineo;
     private String fatorRh;
     private Blob foto;
     private String url;
     private BigDecimal etniaTab;
     private BigDecimal etniaItem;
     private BigDecimal deficienciaTab;
     private BigDecimal deficienciaItem;
     private BigDecimal codOperador;
     private Date dtAlteracao;
     private Date hrAlteracao;
     private BigDecimal concorrencia;

    public Alunos() {
    }

	
    public Alunos(BigDecimal idAluno, Pessoas pessoasByIdPessoa, BigDecimal etniaTab, BigDecimal etniaItem, BigDecimal deficienciaTab, BigDecimal codOperador, Date dtAlteracao, Date hrAlteracao, BigDecimal concorrencia) {
        this.idAluno = idAluno;
        this.pessoasByIdPessoa = pessoasByIdPessoa;
        this.etniaTab = etniaTab;
        this.etniaItem = etniaItem;
        this.deficienciaTab = deficienciaTab;
        this.codOperador = codOperador;
        this.dtAlteracao = dtAlteracao;
        this.hrAlteracao = hrAlteracao;
        this.concorrencia = concorrencia;
    }
    public Alunos(BigDecimal idAluno, Pessoas pessoasByIdResponsavel, Pessoas pessoasByIdPessoa, BigDecimal idEscolaFund, BigDecimal idEscolaMedio, BigDecimal idLocalFund, BigDecimal idLocalMedio, BigDecimal idNaturalidade, BigDecimal idTutorFin, BigDecimal anoConcFund, BigDecimal anoConcMedio, BigDecimal cursoFundTab, BigDecimal cursoFundItem, BigDecimal cursoMedioTab, BigDecimal cursoMedioItem, Date dtNascimento, BigDecimal estadoCivilTab, BigDecimal estadoCivilItem, BigDecimal nacionalidadeTab, BigDecimal nacionalidadeItem, String nomeMae, String nomePai, String sexo, String tipoSanguineo, String fatorRh, Blob foto, String url, BigDecimal etniaTab, BigDecimal etniaItem, BigDecimal deficienciaTab, BigDecimal deficienciaItem, BigDecimal codOperador, Date dtAlteracao, Date hrAlteracao, BigDecimal concorrencia) {
       this.idAluno = idAluno;
       this.pessoasByIdResponsavel = pessoasByIdResponsavel;
       this.pessoasByIdPessoa = pessoasByIdPessoa;
       this.idEscolaFund = idEscolaFund;
       this.idEscolaMedio = idEscolaMedio;
       this.idLocalFund = idLocalFund;
       this.idLocalMedio = idLocalMedio;
       this.idNaturalidade = idNaturalidade;
       this.idTutorFin = idTutorFin;
       this.anoConcFund = anoConcFund;
       this.anoConcMedio = anoConcMedio;
       this.cursoFundTab = cursoFundTab;
       this.cursoFundItem = cursoFundItem;
       this.cursoMedioTab = cursoMedioTab;
       this.cursoMedioItem = cursoMedioItem;
       this.dtNascimento = dtNascimento;
       this.estadoCivilTab = estadoCivilTab;
       this.estadoCivilItem = estadoCivilItem;
       this.nacionalidadeTab = nacionalidadeTab;
       this.nacionalidadeItem = nacionalidadeItem;
       this.nomeMae = nomeMae;
       this.nomePai = nomePai;
       this.sexo = sexo;
       this.tipoSanguineo = tipoSanguineo;
       this.fatorRh = fatorRh;
       this.foto = foto;
       this.url = url;
       this.etniaTab = etniaTab;
       this.etniaItem = etniaItem;
       this.deficienciaTab = deficienciaTab;
       this.deficienciaItem = deficienciaItem;
       this.codOperador = codOperador;
       this.dtAlteracao = dtAlteracao;
       this.hrAlteracao = hrAlteracao;
       this.concorrencia = concorrencia;
    }
   
     @Id 

    
    @Column(name="ID_ALUNO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(BigDecimal idAluno) {
        this.idAluno = idAluno;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_RESPONSAVEL")
    public Pessoas getPessoasByIdResponsavel() {
        return this.pessoasByIdResponsavel;
    }
    
    public void setPessoasByIdResponsavel(Pessoas pessoasByIdResponsavel) {
        this.pessoasByIdResponsavel = pessoasByIdResponsavel;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_PESSOA", unique=true, nullable=false)
    public Pessoas getPessoasByIdPessoa() {
        return this.pessoasByIdPessoa;
    }
    
    public void setPessoasByIdPessoa(Pessoas pessoasByIdPessoa) {
        this.pessoasByIdPessoa = pessoasByIdPessoa;
    }

    
    @Column(name="ID_ESCOLA_FUND", precision=22, scale=0)
    public BigDecimal getIdEscolaFund() {
        return this.idEscolaFund;
    }
    
    public void setIdEscolaFund(BigDecimal idEscolaFund) {
        this.idEscolaFund = idEscolaFund;
    }

    
    @Column(name="ID_ESCOLA_MEDIO", precision=22, scale=0)
    public BigDecimal getIdEscolaMedio() {
        return this.idEscolaMedio;
    }
    
    public void setIdEscolaMedio(BigDecimal idEscolaMedio) {
        this.idEscolaMedio = idEscolaMedio;
    }

    
    @Column(name="ID_LOCAL_FUND", precision=22, scale=0)
    public BigDecimal getIdLocalFund() {
        return this.idLocalFund;
    }
    
    public void setIdLocalFund(BigDecimal idLocalFund) {
        this.idLocalFund = idLocalFund;
    }

    
    @Column(name="ID_LOCAL_MEDIO", precision=22, scale=0)
    public BigDecimal getIdLocalMedio() {
        return this.idLocalMedio;
    }
    
    public void setIdLocalMedio(BigDecimal idLocalMedio) {
        this.idLocalMedio = idLocalMedio;
    }

    
    @Column(name="ID_NATURALIDADE", precision=22, scale=0)
    public BigDecimal getIdNaturalidade() {
        return this.idNaturalidade;
    }
    
    public void setIdNaturalidade(BigDecimal idNaturalidade) {
        this.idNaturalidade = idNaturalidade;
    }

    
    @Column(name="ID_TUTOR_FIN", precision=22, scale=0)
    public BigDecimal getIdTutorFin() {
        return this.idTutorFin;
    }
    
    public void setIdTutorFin(BigDecimal idTutorFin) {
        this.idTutorFin = idTutorFin;
    }

    
    @Column(name="ANO_CONC_FUND", precision=22, scale=0)
    public BigDecimal getAnoConcFund() {
        return this.anoConcFund;
    }
    
    public void setAnoConcFund(BigDecimal anoConcFund) {
        this.anoConcFund = anoConcFund;
    }

    
    @Column(name="ANO_CONC_MEDIO", precision=22, scale=0)
    public BigDecimal getAnoConcMedio() {
        return this.anoConcMedio;
    }
    
    public void setAnoConcMedio(BigDecimal anoConcMedio) {
        this.anoConcMedio = anoConcMedio;
    }

    
    @Column(name="CURSO_FUND_TAB", precision=22, scale=0)
    public BigDecimal getCursoFundTab() {
        return this.cursoFundTab;
    }
    
    public void setCursoFundTab(BigDecimal cursoFundTab) {
        this.cursoFundTab = cursoFundTab;
    }

    
    @Column(name="CURSO_FUND_ITEM", precision=22, scale=0)
    public BigDecimal getCursoFundItem() {
        return this.cursoFundItem;
    }
    
    public void setCursoFundItem(BigDecimal cursoFundItem) {
        this.cursoFundItem = cursoFundItem;
    }

    
    @Column(name="CURSO_MEDIO_TAB", precision=22, scale=0)
    public BigDecimal getCursoMedioTab() {
        return this.cursoMedioTab;
    }
    
    public void setCursoMedioTab(BigDecimal cursoMedioTab) {
        this.cursoMedioTab = cursoMedioTab;
    }

    
    @Column(name="CURSO_MEDIO_ITEM", precision=22, scale=0)
    public BigDecimal getCursoMedioItem() {
        return this.cursoMedioItem;
    }
    
    public void setCursoMedioItem(BigDecimal cursoMedioItem) {
        this.cursoMedioItem = cursoMedioItem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_NASCIMENTO", length=7)
    public Date getDtNascimento() {
        return this.dtNascimento;
    }
    
    public void setDtNascimento(Date dtNascimento) {
        this.dtNascimento = dtNascimento;
    }

    
    @Column(name="ESTADO_CIVIL_TAB", precision=22, scale=0)
    public BigDecimal getEstadoCivilTab() {
        return this.estadoCivilTab;
    }
    
    public void setEstadoCivilTab(BigDecimal estadoCivilTab) {
        this.estadoCivilTab = estadoCivilTab;
    }

    
    @Column(name="ESTADO_CIVIL_ITEM", precision=22, scale=0)
    public BigDecimal getEstadoCivilItem() {
        return this.estadoCivilItem;
    }
    
    public void setEstadoCivilItem(BigDecimal estadoCivilItem) {
        this.estadoCivilItem = estadoCivilItem;
    }

    
    @Column(name="NACIONALIDADE_TAB", precision=22, scale=0)
    public BigDecimal getNacionalidadeTab() {
        return this.nacionalidadeTab;
    }
    
    public void setNacionalidadeTab(BigDecimal nacionalidadeTab) {
        this.nacionalidadeTab = nacionalidadeTab;
    }

    
    @Column(name="NACIONALIDADE_ITEM", precision=22, scale=0)
    public BigDecimal getNacionalidadeItem() {
        return this.nacionalidadeItem;
    }
    
    public void setNacionalidadeItem(BigDecimal nacionalidadeItem) {
        this.nacionalidadeItem = nacionalidadeItem;
    }

    
    @Column(name="NOME_MAE", length=60)
    public String getNomeMae() {
        return this.nomeMae;
    }
    
    public void setNomeMae(String nomeMae) {
        this.nomeMae = nomeMae;
    }

    
    @Column(name="NOME_PAI", length=60)
    public String getNomePai() {
        return this.nomePai;
    }
    
    public void setNomePai(String nomePai) {
        this.nomePai = nomePai;
    }

    
    @Column(name="SEXO", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="TIPO_SANGUINEO", length=2)
    public String getTipoSanguineo() {
        return this.tipoSanguineo;
    }
    
    public void setTipoSanguineo(String tipoSanguineo) {
        this.tipoSanguineo = tipoSanguineo;
    }

    
    @Column(name="FATOR_RH", length=1)
    public String getFatorRh() {
        return this.fatorRh;
    }
    
    public void setFatorRh(String fatorRh) {
        this.fatorRh = fatorRh;
    }

    
    @Column(name="FOTO")
    public Blob getFoto() {
        return this.foto;
    }
    
    public void setFoto(Blob foto) {
        this.foto = foto;
    }

    
    @Column(name="URL", length=254)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="ETNIA_TAB", nullable=false, precision=22, scale=0)
    public BigDecimal getEtniaTab() {
        return this.etniaTab;
    }
    
    public void setEtniaTab(BigDecimal etniaTab) {
        this.etniaTab = etniaTab;
    }

    
    @Column(name="ETNIA_ITEM", nullable=false, precision=22, scale=0)
    public BigDecimal getEtniaItem() {
        return this.etniaItem;
    }
    
    public void setEtniaItem(BigDecimal etniaItem) {
        this.etniaItem = etniaItem;
    }

    
    @Column(name="DEFICIENCIA_TAB", nullable=false, precision=22, scale=0)
    public BigDecimal getDeficienciaTab() {
        return this.deficienciaTab;
    }
    
    public void setDeficienciaTab(BigDecimal deficienciaTab) {
        this.deficienciaTab = deficienciaTab;
    }

    
    @Column(name="DEFICIENCIA_ITEM", precision=22, scale=0)
    public BigDecimal getDeficienciaItem() {
        return this.deficienciaItem;
    }
    
    public void setDeficienciaItem(BigDecimal deficienciaItem) {
        this.deficienciaItem = deficienciaItem;
    }

    
    @Column(name="COD_OPERADOR", nullable=false, precision=22, scale=0)
    public BigDecimal getCodOperador() {
        return this.codOperador;
    }
    
    public void setCodOperador(BigDecimal codOperador) {
        this.codOperador = codOperador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ALTERACAO", nullable=false, length=7)
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HR_ALTERACAO", nullable=false, length=7)
    public Date getHrAlteracao() {
        return this.hrAlteracao;
    }
    
    public void setHrAlteracao(Date hrAlteracao) {
        this.hrAlteracao = hrAlteracao;
    }

    
    @Column(name="CONCORRENCIA", nullable=false, precision=22, scale=0)
    public BigDecimal getConcorrencia() {
        return this.concorrencia;
    }
    
    public void setConcorrencia(BigDecimal concorrencia) {
        this.concorrencia = concorrencia;
    }




}


