package model;
// Generated 23/07/2014 08:44:53 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoas generated by hbm2java
 */
@Entity
@Table(name="PESSOAS"
    ,schema="DBSM"
)
public class Pessoas  implements java.io.Serializable {


     private BigDecimal idPessoa;
     private String nomePessoa;
     private String naturezaJuridica;
     private String nomePessoaUp;
     private BigDecimal codOperador;
     private Date dtAlteracao;
     private Date hrAlteracao;
     private BigDecimal concorrencia;
     private Set<Alunos> alunosesForIdResponsavel = new HashSet<Alunos>(0);
     private Set<Alunos> alunosesForIdPessoa = new HashSet<Alunos>(0);

    public Pessoas() {
    }

	
    public Pessoas(BigDecimal idPessoa, String nomePessoa, String naturezaJuridica, BigDecimal codOperador, Date dtAlteracao, Date hrAlteracao, BigDecimal concorrencia) {
        this.idPessoa = idPessoa;
        this.nomePessoa = nomePessoa;
        this.naturezaJuridica = naturezaJuridica;
        this.codOperador = codOperador;
        this.dtAlteracao = dtAlteracao;
        this.hrAlteracao = hrAlteracao;
        this.concorrencia = concorrencia;
    }
    public Pessoas(BigDecimal idPessoa, String nomePessoa, String naturezaJuridica, String nomePessoaUp, BigDecimal codOperador, Date dtAlteracao, Date hrAlteracao, BigDecimal concorrencia, Set<Alunos> alunosesForIdResponsavel, Set<Alunos> alunosesForIdPessoa) {
       this.idPessoa = idPessoa;
       this.nomePessoa = nomePessoa;
       this.naturezaJuridica = naturezaJuridica;
       this.nomePessoaUp = nomePessoaUp;
       this.codOperador = codOperador;
       this.dtAlteracao = dtAlteracao;
       this.hrAlteracao = hrAlteracao;
       this.concorrencia = concorrencia;
       this.alunosesForIdResponsavel = alunosesForIdResponsavel;
       this.alunosesForIdPessoa = alunosesForIdPessoa;
    }
   
     @Id 

    
    @Column(name="ID_PESSOA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(BigDecimal idPessoa) {
        this.idPessoa = idPessoa;
    }

    
    @Column(name="NOME_PESSOA", nullable=false, length=80)
    public String getNomePessoa() {
        return this.nomePessoa;
    }
    
    public void setNomePessoa(String nomePessoa) {
        this.nomePessoa = nomePessoa;
    }

    
    @Column(name="NATUREZA_JURIDICA", nullable=false, length=1)
    public String getNaturezaJuridica() {
        return this.naturezaJuridica;
    }
    
    public void setNaturezaJuridica(String naturezaJuridica) {
        this.naturezaJuridica = naturezaJuridica;
    }

    
    @Column(name="NOME_PESSOA_UP", length=80)
    public String getNomePessoaUp() {
        return this.nomePessoaUp;
    }
    
    public void setNomePessoaUp(String nomePessoaUp) {
        this.nomePessoaUp = nomePessoaUp;
    }

    
    @Column(name="COD_OPERADOR", nullable=false, precision=22, scale=0)
    public BigDecimal getCodOperador() {
        return this.codOperador;
    }
    
    public void setCodOperador(BigDecimal codOperador) {
        this.codOperador = codOperador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ALTERACAO", nullable=false, length=7)
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HR_ALTERACAO", nullable=false, length=7)
    public Date getHrAlteracao() {
        return this.hrAlteracao;
    }
    
    public void setHrAlteracao(Date hrAlteracao) {
        this.hrAlteracao = hrAlteracao;
    }

    
    @Column(name="CONCORRENCIA", nullable=false, precision=22, scale=0)
    public BigDecimal getConcorrencia() {
        return this.concorrencia;
    }
    
    public void setConcorrencia(BigDecimal concorrencia) {
        this.concorrencia = concorrencia;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="pessoasByIdResponsavel")
    public Set<Alunos> getAlunosesForIdResponsavel() {
        return this.alunosesForIdResponsavel;
    }
    
    public void setAlunosesForIdResponsavel(Set alunosesForIdResponsavel) {
        this.alunosesForIdResponsavel = alunosesForIdResponsavel;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="pessoasByIdPessoa")
    public Set<Alunos> getAlunosesForIdPessoa() {
        return this.alunosesForIdPessoa;
    }
    
    public void setAlunosesForIdPessoa(Set alunosesForIdPessoa) {
        this.alunosesForIdPessoa = alunosesForIdPessoa;
    }




}


